// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuCt-B4NG8rKNai4pQpleOhHa2u0wxZ0Q',
    appId: '1:247171727524:web:4a6d0510d56f70b2fc2631',
    messagingSenderId: '247171727524',
    projectId: 'project-d28a7',
    authDomain: 'project-d28a7.firebaseapp.com',
    storageBucket: 'project-d28a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDeU-BSA318rtn_5HZkEqJKALxso8FQWc',
    appId: '1:247171727524:android:e909aec3a00505fdfc2631',
    messagingSenderId: '247171727524',
    projectId: 'project-d28a7',
    storageBucket: 'project-d28a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3MbclsyOBk1SqwAZ6G_KVPQL1Xp44D8M',
    appId: '1:247171727524:ios:7247a20d5f41680dfc2631',
    messagingSenderId: '247171727524',
    projectId: 'project-d28a7',
    storageBucket: 'project-d28a7.appspot.com',
    androidClientId: '247171727524-5t3n16rn72h6gp8n0na8pqfgqdkk2jud.apps.googleusercontent.com',
    iosClientId: '247171727524-6435cigrdablo9bkesb3onmn270slllp.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3MbclsyOBk1SqwAZ6G_KVPQL1Xp44D8M',
    appId: '1:247171727524:ios:7247a20d5f41680dfc2631',
    messagingSenderId: '247171727524',
    projectId: 'project-d28a7',
    storageBucket: 'project-d28a7.appspot.com',
    androidClientId: '247171727524-5t3n16rn72h6gp8n0na8pqfgqdkk2jud.apps.googleusercontent.com',
    iosClientId: '247171727524-6435cigrdablo9bkesb3onmn270slllp.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
